sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gEMdhtXecUv4QTiBSWN1Eps1K/LGeSAmNvOyDYooKcvjNG6MUyEEgREBSu057FyoNc2sXHPw7I42VGk6IcHy4mSEWXcNoO6kN8DNSKEPpBwpiYOtMX2V8HF36+zxVzg9HNrm3dSEtbAd5/EwXc799nT5xz9eMCgSN1jgSd88xDL52VJRQc6Q+N3w/NVmUFc7Y+Vke9DaPhgcYcq384Fl1ezy+5OwZSg7M4NDKtC9OWDlyl16c1ynDKLyuVt7DogL4bKoub0YbQnaoB9vs+eWEmf/XX7gOlmx2OorvdFgu1eG2NPXSzeAGfq8Nrq8++M4/N0AEUO6lnLytwRFPdUusPgiPIqld7ql1Jp7kFrSXgNSE1+EHZiYx+q8EpWpy+tKCDP/Rv+fNQtG2mhXpsOnlLxQDgW0V0aIR9Hc8fmu24qDgcr2qFENHw875u7TgBpvHYxPPAeinzq+khvuBCrnEbXUiVjKKvFkHCrHdrkl70wgcUbXoiAuMxAO38odX05MBe1gTon17VrQZ5griz1NfeJis1IuxjovCV/y3qCTdPV2idWLBVUHbCbfgu2Nt+OErXheqb4TszpHfiVfeAdHFn7a+s+nBBxWDffwq8l7lFJwt3CHUJqh7JSHN1U54pBFdJDRpS3rt+0c7TtlyNmfaT8K4qZTkyCWpAu6y7WsGuc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Creatures-That-Once-Were-Men_681
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy